siteTitle = "Blog by David Israwi"
siteDescr = "Software Developer | CS Student at Univerisity of Central Florida."
siteAuthor = "David Israwi"

siteGithubUrl = "https://github.com/DavidIsrawi"
siteEmailUrl = "mailto:davidisrawi@gmail.com?Subject=Hello%20David"
siteInstagramUrl = "https://www.instagram.com/davidisrawi"
siteLinkedInUrl = "https://www.linkedin.com/in/davidisrawi"
siteResumeUrl = "https://drive.google.com/open?id=0BxHec4yAhjE_TExsYjlRbUcyLVU"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
